# ----------------------------------------------------------------------------
#
# Package             : dask-ml
# Source Repo         : https://github.com/dask/dask-ml
# Travis Job Link     : https://travis-ci.com/github/asellappen/dask-ml/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: python
dist: bionic
arch:
  - amd64
  - ppc64le

matrix:
  include:
  - env: PYTHON_VERSION=3.6
  - env: PYTHON_VERSION=3.7
  - env: PYTHON_VERSION=3.8
  - env: PYTHON_VERSION=3.6
    arch: ppc64le
  - env: PYTHON_VERSION=3.7
    arch: ppc64le
  - env: PYTHON_VERSION=3.8  
    arch: ppc64le

sudo: required
before_install:
  - sudo apt-get install gfortran libopenblas-dev liblapack-dev
  - sudo apt-get install -y python-pygraphviz
  - export envFile='ci/environment-3.7.yaml'
  - if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
        wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.9.2-Linux-ppc64le.sh -O miniconda.sh; 
    else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda config --set auto_update_conda False
  - conda update -q --all
  - conda install python=$PYTHON_VERSION pip  pytest-xdist pytest
  - pip install pytest-mock
  - pip install python-coveralls --no-cache-dir
  - pip install "dask[dataframe]" --no-cache-dir
#  - conda install llvmlite==0.36.0rc1  -c numba
  - conda install numba isort
  - python -m pip install --no-deps numpy==1.20
  - python -m pip install numpy==1.20.1 --no-cache-dir
  - conda install scikit-image distributed 
  - conda install -c power  scikit-learn
  - pip install dask_glm --no-cache-dir
  - conda env create --quiet --file=$envFile --name=dask-ml-test && conda list -n dask-ml-test
   
install:
  -  python -m pip install --quiet --no-deps -e .

script: 
   #- tests/model_selection/test_incremental.py not supported for ppc
   -  travis_wait 20  python -m pytest -v tests -n10
   #- if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then 
   #    python -m pytest -v tests -n6 --ignore=dask/array/slicing.py --ignore=tests/test_kmeans.py   --ignore=tests/test_spectral_clustering.py  --ignore=tests/model_selection/test_incremental.py;
   #  else
   #    python -m pytest -v tests -n6 --ignore=dask/array/slicing.py --ignore=tests/test_kmeans.py   --ignore=tests/test_spectral_clustering.py;
   #  fi
